language: node_js
node_js:
- 7.9.0
addons:
  ssh_known_hosts: 45.55.26.42
script: echo "skipping test"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_e4ee02218788_key -iv $encrypted_e4ee02218788_iv
    -in travis_dokku_test.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master
